### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by JP24** [biokys/cropimage#14]
Hi, Please help.
I am running the sample project which came with the library, I am using Samsung Galaxy S2 - Skyrocket with Android 4.1.2
So I am getting this error  (Canvas: trying to use a recycled bitmap) only at the first launch and first click on "Take picture". so once I take picture then instead of start crop intent the app crashes.
this error never comes back unless I uninstall app from device and re launch it after new installation.

Following is the error I am getting:

08-22 22:59:33.075: E/AndroidRuntime(14947): FATAL EXCEPTION: Thread-47491
08-22 22:59:33.075: E/AndroidRuntime(14947): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@421fd9b0
08-22 22:59:33.075: E/AndroidRuntime(14947):    at android.graphics.Canvas.throwIfRecycled(Canvas.java:1026)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at android.graphics.Canvas.drawBitmap(Canvas.java:1096)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at android.graphics.Bitmap.createBitmap(Bitmap.java:604)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at eu.janmuller.android.simplecropimage.CropImage$1.prepareBitmap(CropImage.java:572)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at eu.janmuller.android.simplecropimage.CropImage$1.run(CropImage.java:578)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at eu.janmuller.android.simplecropimage.CropImage$6.run(CropImage.java:285)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at eu.janmuller.android.simplecropimage.Util$BackgroundJob.run(Util.java:175)
08-22 22:59:33.075: E/AndroidRuntime(14947):    at java.lang.Thread.run(Thread.java:856)

Please help.
Thanks!

**Comment by raphaelbgr** [comment]
Temporarely fixed by reinstantiating the last screen, isntead of trying to go back to it.
