### ISSUE TITLE
Trying to recycle Bitmap 

### ISSUE THREAD

**Issue by ManojMM026** [biokys/cropimage#27]
Hi i am getting strange exception when i take picture from camera and try to crop it.
Here is my log cat.

I am facing this issue on Galaxy Grand with os 4.2.2

11-25 17:44:28.909: E/AndroidRuntime(30645): FATAL EXCEPTION: Thread-6510
11-25 17:44:28.909: E/AndroidRuntime(30645): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@42765a00
11-25 17:44:28.909: E/AndroidRuntime(30645):    at android.graphics.Canvas.throwIfRecycled(Canvas.java:1026)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at android.graphics.Canvas.drawBitmap(Canvas.java:1096)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at android.graphics.Bitmap.createBitmap(Bitmap.java:646)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at eu.janmuller.android.simplecropimage.CropImage$1.prepareBitmap(CropImage.java:558)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at eu.janmuller.android.simplecropimage.CropImage$1.run(CropImage.java:564)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at eu.janmuller.android.simplecropimage.CropImage$6.run(CropImage.java:271)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at eu.janmuller.android.simplecropimage.Util$BackgroundJob.run(Util.java:175)
11-25 17:44:28.909: E/AndroidRuntime(30645):    at java.lang.Thread.run(Thread.java:856)

**Comment by timtianyang** [comment]
Thanks, I have exactly the same problem.
